# Added by Codex: same-model candidate reranker; not part of the original starter repository.

from __future__ import annotations

import argparse
import json
import string
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

CODEX_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = CODEX_ROOT.parent
sys.path.insert(0, str(CODEX_ROOT))
sys.path.insert(0, str(REPO_ROOT))

from tqdm import tqdm

from judger import Judger
from math_comp.data import answer_slot_count, batched, has_gold, index_by_id, is_mcq, read_jsonl, write_jsonl
from math_comp.final_answer import final_answer_diagnostics, final_format_contract, normalize_final_response
from math_comp.prompts import format_options
from math_comp.scoring import extract_answer_key, score_item, summarize_results
from math_comp.vllm_helpers import add_vllm_cli_args, make_llm, make_sampling_params, vllm_text


SYSTEM = (
    "You are Qwen/Qwen3-4B-Thinking-2507 selecting the best final answer for a math competition problem. "
    "Use only the problem statement and candidate outputs generated by the same Qwen model. "
    "Verify candidates against the problem, prefer exact symbolic forms, and solve directly only if all candidates are wrong. "
    "Obey the requested final-answer schema exactly. Do not call tools."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Use Qwen to rerank or synthesize among Qwen candidate traces.")
    parser.add_argument("--data", default="data/public.jsonl", help="Competition data JSONL.")
    parser.add_argument(
        "--responses",
        nargs="+",
        required=True,
        help="One or more JSONL files with id/response rows, usually finalized candidate outputs.",
    )
    parser.add_argument("--output", default="codex_added/results/reranked.jsonl", help="Reranked JSONL output.")
    parser.add_argument("--model-id", default="Qwen/Qwen3-4B-Thinking-2507", help="Base model id.")
    parser.add_argument("--adapter-dir", default=None, help="Optional PEFT/LoRA adapter directory.")
    parser.add_argument("--limit", type=int, default=None, help="Limit number of data rows after offset.")
    parser.add_argument("--offset", type=int, default=0, help="Skip first N data rows.")
    parser.add_argument("--max-candidates", type=int, default=8, help="Maximum candidates shown per problem.")
    parser.add_argument("--max-response-chars", type=int, default=800, help="Tail chars from each final response.")
    parser.add_argument("--max-trace-chars", type=int, default=1200, help="Tail chars from source reasoning per candidate.")
    parser.add_argument("--max-input-tokens", type=int, default=8192, help="Tokenizer truncation budget.")
    parser.add_argument("--max-new-tokens", type=int, default=1536, help="Reranker generation budget.")
    parser.add_argument("--temperature", type=float, default=0.1, help="Reranker temperature.")
    parser.add_argument("--top-p", type=float, default=0.9, help="Reranker top-p.")
    parser.add_argument(
        "--assistant-mode",
        choices=["think", "direct"],
        default="think",
        help="Use the model's thinking template or suppress the forced thinking prefill for faster direct reranking.",
    )
    parser.add_argument("--dedupe-answer-keys", action="store_true", help="Show only one candidate per answer key.")
    parser.add_argument("--only-conflicts", action="store_true", help="Only rerank rows with multiple answer keys.")
    parser.add_argument("--include-missing", action="store_true", help="Also solve data rows with no candidates.")
    parser.add_argument("--score", action="store_true", help="Score output when data has answers.")
    add_vllm_cli_args(parser)
    return parser.parse_args()


def load_transformers_model(model_id: str, adapter_dir: str | None) -> tuple[Any, Any]:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        trust_remote_code=True,
        dtype=torch.bfloat16,
        device_map="auto",
    )
    if adapter_dir:
        from peft import PeftModel

        model = PeftModel.from_pretrained(model, adapter_dir)
    model.eval()
    return tokenizer, model


def load_vllm_model(args: argparse.Namespace) -> tuple[Any, Any]:
    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    llm = make_llm(args.model_id, args, trust_remote_code=True, adapter_dir=args.adapter_dir)
    return tokenizer, llm


def candidate_label(index: int) -> str:
    if index < len(string.ascii_uppercase):
        return string.ascii_uppercase[index]
    return f"C{index + 1}"


def read_candidates(paths: list[str], data_by_id: dict[int, dict[str, Any]]) -> dict[int, list[dict[str, Any]]]:
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for path in paths:
        for row_index, row in enumerate(read_jsonl(path)):
            item_id = int(row["id"])
            item = data_by_id.get(item_id)
            if not item:
                continue
            response = str(row.get("response", ""))
            key = str(row.get("answer_key") or extract_answer_key(item, response, strict=True))
            grouped[item_id].append(
                {
                    **row,
                    "answer_key": key,
                    "source_file": path,
                    "source_row": row_index,
                }
            )
    return grouped


def select_candidates(
    item: dict[str, Any],
    rows: list[dict[str, Any]],
    max_candidates: int,
    dedupe_answer_keys: bool,
) -> list[dict[str, Any]]:
    if not rows:
        return []

    scored_rows: list[tuple[int, int, int, dict[str, Any]]] = []
    for index, row in enumerate(rows):
        key = str(row.get("answer_key", ""))
        vote_count = int(row.get("vote_count") or 1)
        trace_len = len(str(row.get("source_response") or row.get("response") or ""))
        has_key = 1 if key else 0
        scored_rows.append((-has_key, -vote_count, -trace_len, {**row, "_original_order": index}))

    selected: list[dict[str, Any]] = []
    seen_keys: set[str] = set()
    for _, _, _, row in sorted(scored_rows, key=lambda item: (item[0], item[1], item[2], item[3]["_original_order"])):
        key = str(row.get("answer_key", ""))
        if dedupe_answer_keys and key in seen_keys:
            continue
        selected.append(row)
        seen_keys.add(key)
        if len(selected) >= max_candidates:
            break
    return selected


def build_problem_block(item: dict[str, Any]) -> str:
    question = str(item["question"])
    if item.get("options"):
        question += "\n\nOptions:\n" + format_options(item["options"])
    return question


def build_candidate_block(row: dict[str, Any], index: int, max_response_chars: int, max_trace_chars: int) -> str:
    response = str(row.get("response", ""))[-max_response_chars:]
    source_response = str(row.get("source_response", ""))
    trace = source_response[-max_trace_chars:] if source_response else ""
    parts = [
        f"Candidate {candidate_label(index)}",
        f"answer_key: {row.get('answer_key', '')}",
        f"final_response_tail:\n{response}",
    ]
    variant = row.get("variant")
    sample_index = row.get("sample_index")
    if variant is not None or sample_index is not None:
        parts.insert(1, f"source: variant={variant}, sample_index={sample_index}")
    if trace:
        parts.append(f"reasoning_tail:\n{trace}")
    return "\n".join(parts)


def build_user_prompt(
    item: dict[str, Any],
    candidates: list[dict[str, Any]],
    max_response_chars: int,
    max_trace_chars: int,
) -> str:
    format_note = final_format_contract(item)
    candidate_text = (
        "\n\n".join(
            build_candidate_block(row, index, max_response_chars, max_trace_chars)
            for index, row in enumerate(candidates)
        )
        if candidates
        else "No candidates are available. Solve the problem directly."
    )
    return (
        "Problem:\n"
        f"{build_problem_block(item)}\n\n"
        "Required final-answer schema:\n"
        f"{format_note}\n\n"
        "Candidate outputs:\n"
        f"{candidate_text}\n\n"
        "Select or synthesize the correct answer, then output only the required final-answer line."
    )


def build_prompt(
    tokenizer: Any,
    item: dict[str, Any],
    candidates: list[dict[str, Any]],
    max_response_chars: int,
    max_trace_chars: int,
    assistant_mode: str,
) -> str:
    messages = [
        {"role": "system", "content": SYSTEM},
        {
            "role": "user",
            "content": build_user_prompt(item, candidates, max_response_chars, max_trace_chars),
        },
    ]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    if assistant_mode == "direct":
        forced_think = "<|im_start|>assistant\n<think>\n"
        if text.endswith(forced_think):
            text = text[: -len(forced_think)] + "<|im_start|>assistant\n"
    return text


def unique_answer_keys(candidates: list[dict[str, Any]]) -> set[str]:
    return {str(candidate.get("answer_key", "")) for candidate in candidates if str(candidate.get("answer_key", ""))}


def make_row_from_response(
    item: dict[str, Any],
    response: str,
    candidates: list[dict[str, Any]],
    decision: str,
    score_judger: Judger,
    score: bool,
) -> dict[str, Any]:
    response = normalize_final_response(item, response)
    row = {
        "id": int(item["id"]),
        "is_mcq": is_mcq(item),
        "response": response,
        "answer_key": extract_answer_key(item, response, strict=True),
        "num_candidates": len(candidates),
        "candidate_answer_keys": [str(candidate.get("answer_key", "")) for candidate in candidates],
        "decision": decision,
    }
    row.update(final_answer_diagnostics(item, response))
    if score and has_gold(item):
        row["gold"] = item["answer"]
        row["correct"] = score_item(score_judger, item, response)
    return row


def prepare_rerank_jobs(
    ordered_items: list[dict[str, Any]],
    grouped: dict[int, list[dict[str, Any]]],
    args: argparse.Namespace,
    score_judger: Judger,
) -> tuple[list[dict[str, Any] | None], list[dict[str, Any]]]:
    rows: list[dict[str, Any] | None] = []
    jobs: list[dict[str, Any]] = []
    for item in tqdm(ordered_items, desc="Preparing rerank"):
        item_id = int(item["id"])
        candidates = select_candidates(
            item,
            grouped.get(item_id, []),
            args.max_candidates,
            args.dedupe_answer_keys,
        )
        if args.only_conflicts and candidates and len(unique_answer_keys(candidates)) <= 1:
            rows.append(
                make_row_from_response(
                    item,
                    str(candidates[0].get("response", "")),
                    candidates,
                    "kept_unanimous",
                    score_judger,
                    args.score,
                )
            )
            continue

        rows.append(None)
        jobs.append({"row_index": len(rows) - 1, "item": item, "candidates": candidates})
    return rows, jobs


def rerank_with_transformers(
    ordered_items: list[dict[str, Any]],
    grouped: dict[int, list[dict[str, Any]]],
    args: argparse.Namespace,
    score_judger: Judger,
) -> list[dict[str, Any]]:
    import torch

    tokenizer, model = load_transformers_model(args.model_id, args.adapter_dir)
    rows, jobs = prepare_rerank_jobs(ordered_items, grouped, args, score_judger)
    for job in tqdm(jobs, desc="Reranking"):
        item = job["item"]
        candidates = job["candidates"]
        prompt = build_prompt(
            tokenizer,
            item,
            candidates,
            args.max_response_chars,
            args.max_trace_chars,
            args.assistant_mode,
        )
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=args.max_input_tokens).to(model.device)
        with torch.no_grad():
            output = model.generate(
                **inputs,
                max_new_tokens=args.max_new_tokens,
                do_sample=args.temperature > 0,
                temperature=args.temperature,
                top_p=args.top_p,
                pad_token_id=tokenizer.eos_token_id,
            )
        new_tokens = output[0, inputs["input_ids"].shape[1] :]
        response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        rows[int(job["row_index"])] = make_row_from_response(item, response, candidates, "reranked", score_judger, args.score)
    return [row for row in rows if row is not None]


def rerank_with_vllm(
    ordered_items: list[dict[str, Any]],
    grouped: dict[int, list[dict[str, Any]]],
    args: argparse.Namespace,
    score_judger: Judger,
) -> list[dict[str, Any]]:
    tokenizer, llm = load_vllm_model(args)
    rows, jobs = prepare_rerank_jobs(ordered_items, grouped, args, score_judger)
    sampling_params = make_sampling_params(
        max_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_p=args.top_p,
        do_sample=args.temperature > 0,
    )
    chunk_size = int(args.vllm_batch_size or len(jobs) or 1)
    for batch in tqdm(list(batched(jobs, chunk_size)), desc="Reranking"):
        prompts = [
            build_prompt(
                tokenizer,
                job["item"],
                job["candidates"],
                args.max_response_chars,
                args.max_trace_chars,
                args.assistant_mode,
            )
            for job in batch
        ]
        outputs = llm.generate(prompts, sampling_params=sampling_params)
        for job, output in zip(batch, outputs):
            item = job["item"]
            candidates = job["candidates"]
            rows[int(job["row_index"])] = make_row_from_response(
                item,
                vllm_text(output),
                candidates,
                "reranked",
                score_judger,
                args.score,
            )
    return [row for row in rows if row is not None]


def main() -> None:
    args = parse_args()
    data = read_jsonl(args.data)
    if args.offset:
        data = data[args.offset :]
    if args.limit is not None:
        data = data[: args.limit]

    data_by_id = index_by_id(data)
    grouped = read_candidates(args.responses, data_by_id)
    ordered_items = [item for item in data if args.include_missing or int(item["id"]) in grouped]

    print(f"Reranking {len(ordered_items)} problems from {len(args.responses)} response file(s).")
    score_judger = Judger(strict_extract=False)
    if args.backend == "vllm":
        rows = rerank_with_vllm(ordered_items, grouped, args, score_judger)
    else:
        rows = rerank_with_transformers(ordered_items, grouped, args, score_judger)

    write_jsonl(args.output, rows)
    print(f"Wrote reranked responses to {args.output}")
    if args.score:
        print(json.dumps(summarize_results(rows), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
